replicaCount: 2
image:
  repository: ghcr.io/rsk0-app/orders-service
  tag: 43ed436bf403dc6e207772d77a8811c1bfb2d1b4
  pullPolicy: Always
service:
  port: 80
  targetPort: 8080
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
env:
  ENVIRONMENT: production
  ORDERS_BATCH_SIZE: "1000"
  MEM_FOOTPRINT_MB: "150"
database:
  url: postgres://stand:standpass@postgres.rsk0-apps.svc.cluster.local:5432/stand
downstream:
  url: http://payments-api-payments-api.rsk0-apps.svc.cluster.local
  timeoutMs: 800
inventory:
  url: http://inventory-service-inventory-service.rsk0-apps.svc.cluster.local
failure:
  mode: ""
  errorRate: "0"
  latencyMs: "0"
