apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-orders-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
