apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-orders-service
  labels:
    app: {{ .Values.appLabel | default "orders-service" | quote }}
spec:
  selector:
    app: {{ .Values.appLabel | default "orders-service" | quote }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
